export interface Building {
    code: string;
    name: string;
}

export const BUILDINGS: Building[] = [
    { code: 'GL', name: 'Global' },
    { code: 'A', name: 'Rusun Guru' },
    { code: 'A.1', name: 'Rusun Guru' },
    { code: 'B', name: 'Asrama Putra SD' },
    { code: 'B.1', name: 'Asrama Putra SD' },
    { code: 'C', name: 'Asrama Putri SD' },
    { code: 'C.1', name: 'Asrama Putri SD' },
    { code: 'D', name: 'Asrama Putri SMP' },
    { code: 'D.1', name: 'Asrama Putra SMP' },
    { code: 'E', name: 'Asrama Putra SMA' },
    { code: 'E.1', name: 'Asrama Putri SMA' },
    { code: 'F', name: 'Kantin SD' },
    { code: 'F.1', name: 'Kantin SMP' },
    { code: 'F.2', name: 'Kantin SMA' },
    { code: 'G', name: 'Dapur Gudang' },
    { code: 'H', name: 'Guest House' },
    { code: 'I', name: 'Gedung SMA' },
    { code: 'J', name: 'Gedung SMP' },
    { code: 'K', name: 'Gedung SD' },
    { code: 'L', name: 'Masjid' },
    { code: 'M', name: 'Gedung Serbaguna' },
    { code: 'N', name: 'Lapangan Upacara' },
    { code: 'O', name: 'Pos Keamanan' },
    { code: 'P', name: 'Rumah Pompa' },
    { code: 'Q', name: 'Power House' },
    { code: 'R', name: 'TPS' },
    { code: 'S', name: 'Gedung Ibadah' },
    { code: 'T', name: 'Lapangan Basket' },
    { code: 'U', name: 'Lapangan Sepak Bola' },
    { code: 'V', name: 'Gudang Perawatan' },
    { code: 'T01', name: 'Direksi Keet' },
];

export const WORK_HIERARCHY = [
    {
        category: 'K3 dan Keselamatan',
        tasks: [
            'K3_Safety_Induction',
            'K3_Toolbox_Meeting_Briefing',
            'K3_Safety_Morning_Talk',
            'K3_Audit_Internal_Weekly',
            'K3_Inspeksi_APD_Pekerja',
            'K3_Pemasangan_Safety_Sign_Rambu',
            'K3_Pemasangan_Safety_Net_Jaring',
            'K3_Pemasangan_Railing_Pengaman',
            'K3_Pemasangan_Barikade_Proyek',
            'K3_Inspeksi_Alat_Berat_SILO',
            'K3_Izin_Kerja_Hot_Work',
            'K3_Izin_Kerja_Ketinggian',
            'K3_Pelatihan_Tanggap_Darurat',
            'K3_Penyediaan_Kotak_P3K',
            'K3_Fogging_Area_Proyek'
        ]
    },
    {
        category: 'Persiapan',
        tasks: [
            'Persiapan_Pembersihan_Lahan_Clearing',
            'Persiapan_Pagar_Proyek_Sementara',
            'Persiapan_Pemasangan_Bouwplank_Uitzet',
            'Persiapan_Pembuatan_Direksi_Keet',
            'Persiapan_Pembuatan_Gudang_Material',
            'Persiapan_Pembuatan_Barak_Kerja',
            'Persiapan_Papan_Nama_Proyek_SMKK',
            'Persiapan_Penyediaan_Air_Kerja',
            'Persiapan_Penyediaan_Listrik_Kerja',
            'Persiapan_Mobilisasi_Alat_Berat',
            'Persiapan_Pengukuran_Topografi_Survey',
            'Persiapan_Pembuatan_Jalan_Akses_Site'
        ]
    },
    {
        category: 'Tanah',
        tasks: [
            'Tanah_Galian_Fondasi_Struktur',
            'Tanah_Galian_Basement_Mass',
            'Tanah_Galian_Septic_Tank_Biofil',
            'Tanah_Galian_Saluran_Drainase',
            'Tanah_Pembuangan_Tanah_Sisa_Galian',
            'Tanah_Urugan_Tanah_Kembali_Padat',
            'Tanah_Urugan_Tanah_Peninggian_Lahan',
            'Tanah_Urugan_Pasir_Bawah_Pondasi',
            'Tanah_Urugan_Sirtu_Padat_Vibrator',
            'Tanah_Pemadatan_Tanah_Wacker',
            'Tanah_Lantai_Kerja_Beton_B0_K100',
            'Tanah_Pemasangan_Plastik_Cor_Membrane'
        ]
    },
    {
        category: 'Struktur Bawah',
        tasks: [
            'Struktur_Bawah_Tiang_Pancang_Mobilisasi',
            'Struktur_Bawah_Tiang_Pancang_Pemancangan',
            'Struktur_Bawah_Tiang_Pancang_Sambungan_Las',
            'Struktur_Bawah_Tiang_Pancang_Chipping_Pile',
            'Struktur_Bawah_Bore_Pile_Pengeboran',
            'Struktur_Bawah_Bore_Pile_Instalasi_Besi',
            'Struktur_Bawah_Bore_Pile_Pengecoran_Tremie',
            'Struktur_Bawah_Pile_Cap_Galian',
            'Struktur_Bawah_Pile_Cap_Pembesian',
            'Struktur_Bawah_Pile_Cap_Bekisting',
            'Struktur_Bawah_Pile_Cap_Pengecoran',
            'Struktur_Bawah_Tie_Beam_Galian',
            'Struktur_Bawah_Tie_Beam_Pembesian',
            'Struktur_Bawah_Tie_Beam_Bekisting',
            'Struktur_Bawah_Tie_Beam_Pengecoran',
            'Struktur_Bawah_Kolom_Pedestal_Pembesian',
            'Struktur_Bawah_Kolom_Pedestal_Bekisting',
            'Struktur_Bawah_Kolom_Pedestal_Pengecoran',
            'Struktur_Bawah_Pondasi_Batu_Kali_Belah',
            'Struktur_Bawah_Pondasi_Tapak_Pembesian',
            'Struktur_Bawah_Pondasi_Tapak_Pengecoran',
            'Struktur_Bawah_Pengujian_PDA_Test',
            'Struktur_Bawah_Pengujian_Sondir_Ulang'
        ]
    },
    {
        category: 'Struktur Atas',
        tasks: [
            'Struktur_Atas_Kolom_Utama_Pembesian',
            'Struktur_Atas_Kolom_Utama_Bekisting',
            'Struktur_Atas_Kolom_Utama_Pengecoran',
            'Struktur_Atas_Kolom_Praktis_Pembesian',
            'Struktur_Atas_Kolom_Praktis_Bekisting',
            'Struktur_Atas_Kolom_Praktis_Pengecoran',
            'Struktur_Atas_Balok_Utama_Scaffolding',
            'Struktur_Atas_Balok_Utama_Pembesian',
            'Struktur_Atas_Balok_Utama_Bekisting',
            'Struktur_Atas_Balok_Utama_Pengecoran',
            'Struktur_Atas_Balok_Anak_Pembesian',
            'Struktur_Atas_Balok_Anak_Bekisting',
            'Struktur_Atas_Balok_Anak_Pengecoran',
            'Struktur_Atas_Plat_Lantai_Bondek',
            'Struktur_Atas_Plat_Lantai_Wiremesh',
            'Struktur_Atas_Plat_Lantai_Bekisting',
            'Struktur_Atas_Plat_Lantai_Pengecoran',
            'Struktur_Atas_Plat_Lantai_Finish_Trowel',
            'Struktur_Atas_Ring_Balok_Pembesian',
            'Struktur_Atas_Ring_Balok_Bekisting',
            'Struktur_Atas_Ring_Balok_Pengecoran',
            'Struktur_Atas_Tangga_Pembesian',
            'Struktur_Atas_Tangga_Bekisting',
            'Struktur_Atas_Tangga_Pengecoran',
            'Struktur_Atas_ShearWall_Pembesian',
            'Struktur_Atas_ShearWall_Bekisting',
            'Struktur_Atas_ShearWall_Pengecoran',
            'Struktur_Atas_Bongkar_Bekisting_Kolom',
            'Struktur_Atas_Bongkar_Bekisting_Balok',
            'Struktur_Atas_Bongkar_Bekisting_Plat',
            'Struktur_Atas_Curing_Beton_Watering',
            'Struktur_Atas_Curing_Beton_Compound'
        ]
    },
    {
        category: 'Arsitektur',
        tasks: [
            'Arsitektur_Dinding_Pasang_Bata_Merah',
            'Arsitektur_Dinding_Pasang_Bata_Ringan',
            'Arsitektur_Dinding_Plesteran_Kasar',
            'Arsitektur_Dinding_Plesteran_Halus',
            'Arsitektur_Dinding_Pemasangan_Sponengan',
            'Arsitektur_Dinding_Acian_Semen',
            'Arsitektur_Dinding_Acian_Skimcoat',
            'Arsitektur_Dinding_Cat_Plamir',
            'Arsitektur_Dinding_Cat_Interior',
            'Arsitektur_Dinding_Cat_Eksterior_Weather',
            'Arsitektur_Dinding_Pasang_Wallpaper',
            'Arsitektur_Lantai_Pasir_Bawah_Lantai',
            'Arsitektur_Lantai_Pasang_Keramik_Utama',
            'Arsitektur_Lantai_Pasang_Keramik_KM',
            'Arsitektur_Lantai_Pasang_Granit_Tile',
            'Arsitektur_Lantai_Pasang_Parquet_Vinyl',
            'Arsitektur_Lantai_Pasang_Plint_Lantai',
            'Arsitektur_Plafon_Rangka_Galfum',
            'Arsitektur_Plafon_Pasang_Gypsum',
            'Arsitektur_Plafon_Pasang_PVC_Drop',
            'Arsitektur_Plafon_Pasang_GRC_Board',
            'Arsitektur_Plafon_Finishing_Cat',
            'Arsitektur_Kusen_Aluminium_Powder',
            'Arsitektur_Kusen_Kayu_Melamine',
            'Arsitektur_Daun_Pintu_Engineering',
            'Arsitektur_Daun_Jendela_Kaca_Clear',
            'Arsitektur_Pasang_Kaca_Tempered',
            'Arsitektur_Pasang_Handle_Kunci',
            'Arsitektur_Sanitary_Pasang_Kloset',
            'Arsitektur_Sanitary_Pasang_Wastafel',
            'Arsitektur_Sanitary_Pasang_Urinoir',
            'Arsitektur_Sanitary_Pasang_Shower',
            'Arsitektur_Sanitary_Pasang_Floor_Drain',
            'Arsitektur_Fasad_Pasang_ACP_Panel',
            'Arsitektur_Fasad_Pasang_Curtain_Wall',
            'Arsitektur_Railing_Tangga_Stainless',
            'Arsitektur_Railing_Balkon_Kaca'
        ]
    },
    {
        category: 'Atap dan Rangka',
        tasks: [
            'Atap_Rangka_Baja_Ringan_C_Channel',
            'Atap_Gording_CNP_Steel',
            'Atap_Insulasi_Aluminium_Foil',
            'Atap_Pasang_Genteng_Metal',
            'Atap_Pasang_Genteng_Keramik',
            'Atap_Pasang_Spandek_Zincalume',
            'Atap_Pasang_Nock_Bubungan',
            'Atap_Pasang_Lisplang_GRC',
            'Atap_Talang_Air_Horizontal',
            'Atap_Finishing_Flashings_Roof'
        ]
    },
    {
        category: 'MEP',
        tasks: [
            'MEP_Listrik_Instalasi_Kabel_TR',
            'MEP_Listrik_Kabel_Power_Genset',
            'MEP_Listrik_Pemasangan_Tray_Kabel',
            'MEP_Listrik_Panel_LVMDP_Unit',
            'MEP_Listrik_Panel_SDP_Lantai',
            'MEP_Listrik_Instalasi_Pipa_Conduit',
            'MEP_Listrik_Titik_Lampu_Penerangan',
            'MEP_Listrik_Pasang_Armatur_Lampu',
            'MEP_Listrik_Pasang_Saklar_StopKontak',
            'MEP_Plumbing_Instalasi_Pipa_Air_Bersih',
            'MEP_Plumbing_Instalasi_Pipa_Air_Kotor',
            'MEP_Plumbing_Instalasi_Pipa_Vent',
            'MEP_Plumbing_Pasang_Pompa_Booster',
            'MEP_Plumbing_Pasang_Roof_Tank_Tandon',
            'MEP_Plumbing_Unit_Bio_Septic_Tank',
            'MEP_HVAC_Instalasi_Pipa_Refrigerant',
            'MEP_HVAC_Unit_Indoor_AC',
            'MEP_HVAC_Unit_Outdoor_AC',
            'MEP_Fire_Instalasi_Smoke_Detector',
            'MEP_Fire_Unit_Pillar_Hydrant',
            'MEP_Fire_Unit_Fire_Extinguisher',
            'MEP_Elektronik_Instalasi_CCTV_IP',
            'MEP_Elektronik_Wifi_Access_Point',
            'MEP_Elektronik_Public_Address_Sound',
            'MEP_Perlindungan_Pasang_Penangkal_Petir',
            'MEP_Perlindungan_Waterproofing_Toilet',
            'MEP_Perlindungan_Waterproofing_Dak_Beton'
        ]
    },
    {
        category: 'Lansekap dan Tapak',
        tasks: [
            'Tapak_Pembersihan_Area_Lansekap',
            'Tapak_Pemasangan_Paving_Block',
            'Tapak_Pemasangan_Cansteen_Beton',
            'Tapak_Pemasangan_Grass_Block',
            'Tapak_Saluran_Drainase_U_Ditch',
            'Tapak_Saluran_Tertutup_Beton_Cover',
            'Tapak_Pemasangan_Lampu_Taman',
            'Tapak_Taman_Rumput_Gajah_Mini',
            'Tapak_Penanaman_Pohon_Peneduh',
            'Tapak_Carparking_Signage_Marking'
        ]
    },
    {
        category: 'Material On Site',
        tasks: [
            'Material_Pasir_Urug_Pasang_Truk',
            'Material_Batu_Kali_Pecah_Split',
            'Material_Semen_PC_Mu_Instant',
            'Material_Besi_Beton_SNI_Pallet',
            'Material_Bata_Ringan_AAC_Pallet',
            'Material_Keramik_Granit_Pallet',
            'Material_Pipa_PVC_PPR_Batang',
            'Material_Beton_Ready_Mix_Lorry',
            'Material_Besi_Wiremesh_Rol_Lembar',
            'Material_Kayu_Meranti_Bekisting_Ikat',
            'Material_Bondek_Galvalume_Lembar',
            'Material_Baja_Ringan_Profil_Ikat'
        ]
    },
    {
        category: 'Dokumentasi & Monitoring',
        tasks: [
            'Dokumentasi_Kondisi_Titik_Nol',
            'Dokumentasi_Progress_Mingguan_Fisik',
            'Dokumentasi_Progress_Bulanan_Fisik',
            'Dokumentasi_Drone_View_Aerial',
            'Dokumentasi_Tes_Uji_Kubus_Beton',
            'Dokumentasi_Tes_Tarik_Baja_Lab',
            'Dokumentasi_Tes_Tekan_Pipa_Hydro',
            'Dokumentasi_Joint_Inspection_Owner',
            'Dokumentasi_Kunjungan_Direksi_Staff',
            'Dokumentasi_Progress_100_Satu_Serah',
            'Dokumentasi_Pelaksanaan_Rapat_Site'
        ]
    }
];
